# Generated by Django 3.0.7 on 2020-06-16 03:33

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('floor_area_size', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=9)),
                ('number_of_rooms', models.SmallIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, help_text='Location Latitude', max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, help_text='Location Longitude', max_digits=9)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
